version: "3"
services:
  node:
    image: node:16
    container_name: Blog-Node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    environment:
      MYSQL_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_HOST: db
      PORT: '3333'

  db:
    image: mysql:5.7
    container_name: Blog-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog_db
    ports:
      - 3306:3306
    

